import React from "react";
import {
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  Link,
  Box,
} from "@mui/material";
import Panel from "../../Overview/Panel/Panel";
import useDashboardColors from "../../Overview/Tokens/Tokens";

const DEFAULT_DATA = [
  {
    name: "Daily Production Report",
    type: "PDF",
    range: "Nov 14, 2024",
    generatedOn: "Nov 14, 2024 10:32 AM",
    by: "S. Kumar",
  },
  {
    name: "Weekly Efficiency Report",
    type: "Excel",
    range: "Nov 8 – Nov 14, 2024",
    generatedOn: "Nov 14, 2024 09:15 AM",
    by: "S. Kumar",
  },
  {
    name: "Operator Performance Report",
    type: "PDF",
    range: "Nov 8 – Nov 14, 2024",
    generatedOn: "Nov 13, 2024 06:45 PM",
    by: "S. Kumar",
  },
  {
    name: "Loss Analysis Report",
    type: "PDF",
    range: "Nov 1 – Nov 14, 2024",
    generatedOn: "Nov 13, 2024 04:20 PM",
    by: "S. Kumar",
  },
  {
    name: "SOP Compliance Report",
    type: "Excel",
    range: "Nov 1 – Nov 14, 2024",
    generatedOn: "Nov 12, 2024 11:30 AM",
    by: "S. Kumar",
  },
];

export default function RecentReports({
  data = DEFAULT_DATA,
  onViewAll,
  onDownload,
}) {
  const c = useDashboardColors();

  const headCell = {
    fontSize: 11.5,
    fontWeight: 600,
    color: c.muted,
    borderBottom: `1px solid ${c.cardBorder}`,
    py: 1,
    whiteSpace: "nowrap",
  };
  const bodyCell = {
    fontSize: 12.5,
    color: c.text,
    borderBottom: `1px solid ${c.cardBorder}`,
    py: 1,
    whiteSpace: "nowrap",
  };

  return (
    <Panel
      title="Recent Reports"
      action="View All Reports"
      onActionClick={onViewAll}
    >
      <Box sx={{ overflowX: "auto" }}>
        <Table size="small" sx={{ "& td, & th": { px: 1 }, minWidth: 720 }}>
          <TableHead>
            <TableRow>
              <TableCell sx={headCell}>Report Name</TableCell>
              <TableCell sx={headCell}>Type</TableCell>
              <TableCell sx={headCell}>Date Range</TableCell>
              <TableCell sx={headCell}>Generated On</TableCell>
              <TableCell sx={headCell}>Generated By</TableCell>
              <TableCell sx={headCell} align="right">
                Download
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {data.map((r, i) => (
              <TableRow key={i} hover>
                <TableCell
                  sx={{ ...bodyCell, fontWeight: 600, color: c.title }}
                >
                  {r.name}
                </TableCell>
                <TableCell sx={bodyCell}>{r.type}</TableCell>
                <TableCell sx={bodyCell}>{r.range}</TableCell>
                <TableCell sx={bodyCell}>{r.generatedOn}</TableCell>
                <TableCell sx={bodyCell}>{r.by}</TableCell>
                <TableCell sx={bodyCell} align="right">
                  <Link
                    component="button"
                    type="button"
                    underline="hover"
                    onClick={() => onDownload?.(r)}
                    sx={{ fontSize: 12.5, fontWeight: 700, color: c.accent }}
                  >
                    Download
                  </Link>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Box>
    </Panel>
  );
}
